//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusOPEN.Website.Admin {
    
    
    public partial class ManageHomepage {
        
        /// <summary>
        /// MessageLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.FeedbackLabel MessageLabel1;
        
        /// <summary>
        /// BrandSelectorPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder BrandSelectorPanel;
        
        /// <summary>
        /// BrandDropDownList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.BrandDropDownList BrandDropDownList1;
        
        /// <summary>
        /// TemplateSelectorPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder TemplateSelectorPanel;
        
        /// <summary>
        /// HomepageTemplateTypeDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.HomepageTypeDropDownList HomepageTemplateTypeDropDownList;
        
        /// <summary>
        /// StandardTemplateEditorPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder StandardTemplateEditorPanel;
        
        /// <summary>
        /// HelpHyperLink1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.HelpHyperLink HelpHyperLink1;
        
        /// <summary>
        /// IntroTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.RichTextBox IntroTextBox;
        
        /// <summary>
        /// CategoryUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel CategoryUpdatePanel;
        
        /// <summary>
        /// CategoriesTreeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.CategoriesTreeView CategoriesTreeView;
        
        /// <summary>
        /// SelectedCategoriesListBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListBox SelectedCategoriesListBox;
        
        /// <summary>
        /// MoveUpCategoryButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button MoveUpCategoryButton;
        
        /// <summary>
        /// MoveDownCategoryButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button MoveDownCategoryButton;
        
        /// <summary>
        /// RemoveCategoryButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button RemoveCategoryButton;
        
        /// <summary>
        /// HomepageImageEditor1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.HomepageImageEditor HomepageImageEditor1;
        
        /// <summary>
        /// HomepageImageEditor2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.HomepageImageEditor HomepageImageEditor2;
        
        /// <summary>
        /// HomepageImageEditor3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.HomepageImageEditor HomepageImageEditor3;
        
        /// <summary>
        /// HomepageImageEditor4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.HomepageImageEditor HomepageImageEditor4;
        
        /// <summary>
        /// CustomHtmlTemplateEditorPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder CustomHtmlTemplateEditorPanel;
        
        /// <summary>
        /// MessageLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.FeedbackLabel MessageLabel2;
        
        /// <summary>
        /// CustomHtmlTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.RichTextBox CustomHtmlTextBox;
        
        /// <summary>
        /// BumperPageUpdatePanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel BumperPageUpdatePanel;
        
        /// <summary>
        /// IncludeBumperPageCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox IncludeBumperPageCheckBox;
        
        /// <summary>
        /// SkipBumperPageCheckBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox SkipBumperPageCheckBox;
        
        /// <summary>
        /// BumperPageHtmlWrapper control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel BumperPageHtmlWrapper;
        
        /// <summary>
        /// BumperPageTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.TextArea BumperPageTextBox;
        
        /// <summary>
        /// LastModifiedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LastModifiedLabel;
        
        /// <summary>
        /// CancelButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FocusOPEN.Website.Controls.CancelButton CancelButton;
        
        /// <summary>
        /// PreviewButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button PreviewButton;
        
        /// <summary>
        /// PublishButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button PublishButton;
    }
}
