USE master
GO

-- Enable CLR
sp_configure 'clr enabled', 1
GO
reconfigure
GO
PRINT 'Enabled CLR'


IF (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = 'FocusOPEN' OR name = 'FocusOPEN')))
BEGIN
	ALTER DATABASE [FocusOPEN] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE [FocusOPEN]
	PRINT 'Dropped old database'
END


CREATE DATABASE [FocusOPEN]
GO
PRINT 'Created database'


EXEC dbo.sp_dbcmptlevel @dbname=N'FocusOPEN', @new_cmptlevel=90
GO
PRINT 'Set compatibility level'


USE [master]
GO
CREATE LOGIN [focusopen] WITH PASSWORD=N'focusopen', DEFAULT_DATABASE=[FocusOPEN], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [FocusOPEN]
GO
CREATE USER [focusopen] FOR LOGIN [focusopen]
GO
USE [FocusOPEN]
GO
EXEC sp_addrolemember N'db_owner', N'focusopen'
GO
PRINT 'Created user'


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FocusOPEN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FocusOPEN] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FocusOPEN] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FocusOPEN] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FocusOPEN] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FocusOPEN] SET ARITHABORT OFF 
GO
ALTER DATABASE [FocusOPEN] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FocusOPEN] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [FocusOPEN] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FocusOPEN] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FocusOPEN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FocusOPEN] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FocusOPEN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FocusOPEN] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FocusOPEN] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FocusOPEN] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FocusOPEN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FocusOPEN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FocusOPEN] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FocusOPEN] SET  READ_WRITE 
GO
ALTER DATABASE [FocusOPEN] SET RECOVERY FULL 
GO
ALTER DATABASE [FocusOPEN] SET  MULTI_USER 
GO
ALTER DATABASE [FocusOPEN] SET PAGE_VERIFY CHECKSUM  
GO
USE [FocusOPEN]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [FocusOPEN] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
