//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 7/3/2011 3:48:57 PM
namespace FocusOPEN.APS
{
    
    /// <summary>
    /// There are no comments for APSEntities in the schema.
    /// </summary>
    public partial class APSEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new APSEntities object using the connection string found in the 'APSEntities' section of the application configuration file.
        /// </summary>
        public APSEntities() : 
                base("name=APSEntities", "APSEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new APSEntities object.
        /// </summary>
        public APSEntities(string connectionString) : 
                base(connectionString, "APSEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new APSEntities object.
        /// </summary>
        public APSEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "APSEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for APSLog in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<APSLog> APSLog
        {
            get
            {
                if ((this._APSLog == null))
                {
                    this._APSLog = base.CreateQuery<APSLog>("[APSLog]");
                }
                return this._APSLog;
            }
        }
        private global::System.Data.Objects.ObjectQuery<APSLog> _APSLog;
        /// <summary>
        /// There are no comments for APSQueuedJob in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<APSQueuedJob> APSQueuedJob
        {
            get
            {
                if ((this._APSQueuedJob == null))
                {
                    this._APSQueuedJob = base.CreateQuery<APSQueuedJob>("[APSQueuedJob]");
                }
                return this._APSQueuedJob;
            }
        }
        private global::System.Data.Objects.ObjectQuery<APSQueuedJob> _APSQueuedJob;
        /// <summary>
        /// There are no comments for APSDebugLog in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<APSDebugLog> APSDebugLog
        {
            get
            {
                if ((this._APSDebugLog == null))
                {
                    this._APSDebugLog = base.CreateQuery<APSDebugLog>("[APSDebugLog]");
                }
                return this._APSDebugLog;
            }
        }
        private global::System.Data.Objects.ObjectQuery<APSDebugLog> _APSDebugLog;
        /// <summary>
        /// There are no comments for APSLog in the schema.
        /// </summary>
        public void AddToAPSLog(APSLog aPSLog)
        {
            base.AddObject("APSLog", aPSLog);
        }
        /// <summary>
        /// There are no comments for APSQueuedJob in the schema.
        /// </summary>
        public void AddToAPSQueuedJob(APSQueuedJob aPSQueuedJob)
        {
            base.AddObject("APSQueuedJob", aPSQueuedJob);
        }
        /// <summary>
        /// There are no comments for APSDebugLog in the schema.
        /// </summary>
        public void AddToAPSDebugLog(APSDebugLog aPSDebugLog)
        {
            base.AddObject("APSDebugLog", aPSDebugLog);
        }
    }
    /// <summary>
    /// There are no comments for APSModel.APSLog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LogId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="APSModel", Name="APSLog")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class APSLog : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new APSLog object.
        /// </summary>
        /// <param name="logId">Initial value of LogId.</param>
        /// <param name="jobId">Initial value of JobId.</param>
        /// <param name="message">Initial value of Message.</param>
        /// <param name="date">Initial value of Date.</param>
        public static APSLog CreateAPSLog(long logId, long jobId, string message, global::System.DateTime date)
        {
            APSLog aPSLog = new APSLog();
            aPSLog.LogId = logId;
            aPSLog.JobId = jobId;
            aPSLog.Message = message;
            aPSLog.Date = date;
            return aPSLog;
        }
        /// <summary>
        /// There are no comments for Property LogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long LogId
        {
            get
            {
                return this._LogId;
            }
            set
            {
                this.OnLogIdChanging(value);
                this.ReportPropertyChanging("LogId");
                this._LogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LogId");
                this.OnLogIdChanged();
            }
        }
        private long _LogId;
        partial void OnLogIdChanging(long value);
        partial void OnLogIdChanged();
        /// <summary>
        /// There are no comments for Property JobId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long JobId
        {
            get
            {
                return this._JobId;
            }
            set
            {
                this.OnJobIdChanging(value);
                this.ReportPropertyChanging("JobId");
                this._JobId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("JobId");
                this.OnJobIdChanged();
            }
        }
        private long _JobId;
        partial void OnJobIdChanging(long value);
        partial void OnJobIdChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    }
    /// <summary>
    /// There are no comments for APSModel.APSQueuedJob in the schema.
    /// </summary>
    /// <KeyProperties>
    /// QueuedJobId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="APSModel", Name="APSQueuedJob")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class APSQueuedJob : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new APSQueuedJob object.
        /// </summary>
        /// <param name="queuedJobId">Initial value of QueuedJobId.</param>
        /// <param name="assetId">Initial value of AssetId.</param>
        /// <param name="inputPath">Initial value of InputPath.</param>
        /// <param name="pluginName">Initial value of PluginName.</param>
        /// <param name="createThumbnail">Initial value of CreateThumbnail.</param>
        /// <param name="createPreview">Initial value of CreatePreview.</param>
        /// <param name="overrideHeight">Initial value of OverrideHeight.</param>
        /// <param name="overrideWidth">Initial value of OverrideWidth.</param>
        /// <param name="dateAdded">Initial value of DateAdded.</param>
        /// <param name="queuedJobStatusId">Initial value of QueuedJobStatusId.</param>
        /// <param name="message">Initial value of Message.</param>
        /// <param name="callbackUrl">Initial value of CallbackUrl.</param>
        /// <param name="additionalData">Initial value of AdditionalData.</param>
        public static APSQueuedJob CreateAPSQueuedJob(long queuedJobId, long assetId, string inputPath, string pluginName, bool createThumbnail, bool createPreview, int overrideHeight, int overrideWidth, global::System.DateTime dateAdded, long queuedJobStatusId, string message, string callbackUrl, string additionalData)
        {
            APSQueuedJob aPSQueuedJob = new APSQueuedJob();
            aPSQueuedJob.QueuedJobId = queuedJobId;
            aPSQueuedJob.AssetId = assetId;
            aPSQueuedJob.InputPath = inputPath;
            aPSQueuedJob.PluginName = pluginName;
            aPSQueuedJob.CreateThumbnail = createThumbnail;
            aPSQueuedJob.CreatePreview = createPreview;
            aPSQueuedJob.OverrideHeight = overrideHeight;
            aPSQueuedJob.OverrideWidth = overrideWidth;
            aPSQueuedJob.DateAdded = dateAdded;
            aPSQueuedJob.QueuedJobStatusId = queuedJobStatusId;
            aPSQueuedJob.Message = message;
            aPSQueuedJob.CallbackUrl = callbackUrl;
            aPSQueuedJob.AdditionalData = additionalData;
            return aPSQueuedJob;
        }
        /// <summary>
        /// There are no comments for Property QueuedJobId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long QueuedJobId
        {
            get
            {
                return this._QueuedJobId;
            }
            set
            {
                this.OnQueuedJobIdChanging(value);
                this.ReportPropertyChanging("QueuedJobId");
                this._QueuedJobId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("QueuedJobId");
                this.OnQueuedJobIdChanged();
            }
        }
        private long _QueuedJobId;
        partial void OnQueuedJobIdChanging(long value);
        partial void OnQueuedJobIdChanged();
        /// <summary>
        /// There are no comments for Property AssetId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long AssetId
        {
            get
            {
                return this._AssetId;
            }
            set
            {
                this.OnAssetIdChanging(value);
                this.ReportPropertyChanging("AssetId");
                this._AssetId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AssetId");
                this.OnAssetIdChanged();
            }
        }
        private long _AssetId;
        partial void OnAssetIdChanging(long value);
        partial void OnAssetIdChanged();
        /// <summary>
        /// There are no comments for Property InputPath in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string InputPath
        {
            get
            {
                return this._InputPath;
            }
            set
            {
                this.OnInputPathChanging(value);
                this.ReportPropertyChanging("InputPath");
                this._InputPath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("InputPath");
                this.OnInputPathChanged();
            }
        }
        private string _InputPath;
        partial void OnInputPathChanging(string value);
        partial void OnInputPathChanged();
        /// <summary>
        /// There are no comments for Property WatermarkPath in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string WatermarkPath
        {
            get
            {
                return this._WatermarkPath;
            }
            set
            {
                this.OnWatermarkPathChanging(value);
                this.ReportPropertyChanging("WatermarkPath");
                this._WatermarkPath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("WatermarkPath");
                this.OnWatermarkPathChanged();
            }
        }
        private string _WatermarkPath;
        partial void OnWatermarkPathChanging(string value);
        partial void OnWatermarkPathChanged();
        /// <summary>
        /// There are no comments for Property PluginName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PluginName
        {
            get
            {
                return this._PluginName;
            }
            set
            {
                this.OnPluginNameChanging(value);
                this.ReportPropertyChanging("PluginName");
                this._PluginName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PluginName");
                this.OnPluginNameChanged();
            }
        }
        private string _PluginName;
        partial void OnPluginNameChanging(string value);
        partial void OnPluginNameChanged();
        /// <summary>
        /// There are no comments for Property CreateThumbnail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreateThumbnail
        {
            get
            {
                return this._CreateThumbnail;
            }
            set
            {
                this.OnCreateThumbnailChanging(value);
                this.ReportPropertyChanging("CreateThumbnail");
                this._CreateThumbnail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateThumbnail");
                this.OnCreateThumbnailChanged();
            }
        }
        private bool _CreateThumbnail;
        partial void OnCreateThumbnailChanging(bool value);
        partial void OnCreateThumbnailChanged();
        /// <summary>
        /// There are no comments for Property CreatePreview in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreatePreview
        {
            get
            {
                return this._CreatePreview;
            }
            set
            {
                this.OnCreatePreviewChanging(value);
                this.ReportPropertyChanging("CreatePreview");
                this._CreatePreview = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatePreview");
                this.OnCreatePreviewChanged();
            }
        }
        private bool _CreatePreview;
        partial void OnCreatePreviewChanging(bool value);
        partial void OnCreatePreviewChanged();
        /// <summary>
        /// There are no comments for Property OverrideHeight in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int OverrideHeight
        {
            get
            {
                return this._OverrideHeight;
            }
            set
            {
                this.OnOverrideHeightChanging(value);
                this.ReportPropertyChanging("OverrideHeight");
                this._OverrideHeight = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OverrideHeight");
                this.OnOverrideHeightChanged();
            }
        }
        private int _OverrideHeight;
        partial void OnOverrideHeightChanging(int value);
        partial void OnOverrideHeightChanged();
        /// <summary>
        /// There are no comments for Property OverrideWidth in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int OverrideWidth
        {
            get
            {
                return this._OverrideWidth;
            }
            set
            {
                this.OnOverrideWidthChanging(value);
                this.ReportPropertyChanging("OverrideWidth");
                this._OverrideWidth = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OverrideWidth");
                this.OnOverrideWidthChanged();
            }
        }
        private int _OverrideWidth;
        partial void OnOverrideWidthChanging(int value);
        partial void OnOverrideWidthChanged();
        /// <summary>
        /// There are no comments for Property DateAdded in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return this._DateAdded;
            }
            set
            {
                this.OnDateAddedChanging(value);
                this.ReportPropertyChanging("DateAdded");
                this._DateAdded = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateAdded");
                this.OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
        /// <summary>
        /// There are no comments for Property DateProcessed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> DateProcessed
        {
            get
            {
                return this._DateProcessed;
            }
            set
            {
                this.OnDateProcessedChanging(value);
                this.ReportPropertyChanging("DateProcessed");
                this._DateProcessed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DateProcessed");
                this.OnDateProcessedChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _DateProcessed;
        partial void OnDateProcessedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateProcessedChanged();
        /// <summary>
        /// There are no comments for Property QueuedJobStatusId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long QueuedJobStatusId
        {
            get
            {
                return this._QueuedJobStatusId;
            }
            set
            {
                this.OnQueuedJobStatusIdChanging(value);
                this.ReportPropertyChanging("QueuedJobStatusId");
                this._QueuedJobStatusId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("QueuedJobStatusId");
                this.OnQueuedJobStatusIdChanged();
            }
        }
        private long _QueuedJobStatusId;
        partial void OnQueuedJobStatusIdChanging(long value);
        partial void OnQueuedJobStatusIdChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property CallbackUrl in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CallbackUrl
        {
            get
            {
                return this._CallbackUrl;
            }
            set
            {
                this.OnCallbackUrlChanging(value);
                this.ReportPropertyChanging("CallbackUrl");
                this._CallbackUrl = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CallbackUrl");
                this.OnCallbackUrlChanged();
            }
        }
        private string _CallbackUrl;
        partial void OnCallbackUrlChanging(string value);
        partial void OnCallbackUrlChanged();
        /// <summary>
        /// There are no comments for Property AdditionalData in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalData
        {
            get
            {
                return this._AdditionalData;
            }
            set
            {
                this.OnAdditionalDataChanging(value);
                this.ReportPropertyChanging("AdditionalData");
                this._AdditionalData = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AdditionalData");
                this.OnAdditionalDataChanged();
            }
        }
        private string _AdditionalData;
        partial void OnAdditionalDataChanging(string value);
        partial void OnAdditionalDataChanged();
    }
    /// <summary>
    /// There are no comments for APSModel.APSDebugLog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// APSDebugLogId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="APSModel", Name="APSDebugLog")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class APSDebugLog : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new APSDebugLog object.
        /// </summary>
        /// <param name="aPSDebugLogId">Initial value of APSDebugLogId.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="thread">Initial value of Thread.</param>
        /// <param name="level">Initial value of Level.</param>
        /// <param name="logger">Initial value of Logger.</param>
        /// <param name="message">Initial value of Message.</param>
        public static APSDebugLog CreateAPSDebugLog(long aPSDebugLogId, global::System.DateTime date, string thread, string level, string logger, string message)
        {
            APSDebugLog aPSDebugLog = new APSDebugLog();
            aPSDebugLog.APSDebugLogId = aPSDebugLogId;
            aPSDebugLog.Date = date;
            aPSDebugLog.Thread = thread;
            aPSDebugLog.Level = level;
            aPSDebugLog.Logger = logger;
            aPSDebugLog.Message = message;
            return aPSDebugLog;
        }
        /// <summary>
        /// There are no comments for Property APSDebugLogId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long APSDebugLogId
        {
            get
            {
                return this._APSDebugLogId;
            }
            set
            {
                this.OnAPSDebugLogIdChanging(value);
                this.ReportPropertyChanging("APSDebugLogId");
                this._APSDebugLogId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("APSDebugLogId");
                this.OnAPSDebugLogIdChanged();
            }
        }
        private long _APSDebugLogId;
        partial void OnAPSDebugLogIdChanging(long value);
        partial void OnAPSDebugLogIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this.ReportPropertyChanging("Date");
                this._Date = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Date");
                this.OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Thread in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Thread
        {
            get
            {
                return this._Thread;
            }
            set
            {
                this.OnThreadChanging(value);
                this.ReportPropertyChanging("Thread");
                this._Thread = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Thread");
                this.OnThreadChanged();
            }
        }
        private string _Thread;
        partial void OnThreadChanging(string value);
        partial void OnThreadChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this.ReportPropertyChanging("Level");
                this._Level = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Level");
                this.OnLevelChanged();
            }
        }
        private string _Level;
        partial void OnLevelChanging(string value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property Logger in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Logger
        {
            get
            {
                return this._Logger;
            }
            set
            {
                this.OnLoggerChanging(value);
                this.ReportPropertyChanging("Logger");
                this._Logger = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Logger");
                this.OnLoggerChanged();
            }
        }
        private string _Logger;
        partial void OnLoggerChanging(string value);
        partial void OnLoggerChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
    }
}
